// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaIOr9HdDmsAfU1ICnrvcCPvzxvMd4y4',
    appId: '1:557355299582:web:c76a08365280b0fcfaabaf',
    messagingSenderId: '557355299582',
    projectId: 'intershala-assignment1',
    authDomain: 'intershala-assignment1.firebaseapp.com',
    storageBucket: 'intershala-assignment1.appspot.com',
    measurementId: 'G-CKVQXXC42V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxbhGQo6msEen2agZlFmdHnrQb7sPf74',
    appId: '1:557355299582:android:ea99749123fc382bfaabaf',
    messagingSenderId: '557355299582',
    projectId: 'intershala-assignment1',
    storageBucket: 'intershala-assignment1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzD9rKfPCW99FENgJlOAb82v9kfrYJWYg',
    appId: '1:557355299582:ios:24ec4472f24f33d6faabaf',
    messagingSenderId: '557355299582',
    projectId: 'intershala-assignment1',
    storageBucket: 'intershala-assignment1.appspot.com',
    iosClientId: '557355299582-c68jufi59rfnvc3qkflkf1hnsdrrg36t.apps.googleusercontent.com',
    iosBundleId: 'com.example.intershalaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzD9rKfPCW99FENgJlOAb82v9kfrYJWYg',
    appId: '1:557355299582:ios:24ec4472f24f33d6faabaf',
    messagingSenderId: '557355299582',
    projectId: 'intershala-assignment1',
    storageBucket: 'intershala-assignment1.appspot.com',
    iosClientId: '557355299582-c68jufi59rfnvc3qkflkf1hnsdrrg36t.apps.googleusercontent.com',
    iosBundleId: 'com.example.intershalaAssignment',
  );
}
